Module7 task1
htmlacademy-react/1309327-what-to-watch-8 pull request #10
Opened 2021-11-10 19:24 UTC by samanna27

2021-11-16 19:52 UTC, dtsaryov requested changes

2021-11-16 19:52 UTC, dtsaryov commented on project/src/components/adaptor/adaptor.ts
> +const defineFilmRating = (rating: number) => {
Задача адаптеров в нашем случае - привести данные с сервера в валидную JS структуру, а тут у нас по факту "форматирование", или формирование отображаемого представления. Поэтому, если это действительно надо, то лучше всего поместить в тот модуль, где это используется

2021-11-16 19:52 UTC, dtsaryov commented on project/src/components/adaptor/adaptor.ts
> +const transferMinutesToDurationString = (minutes: number) => {
Аналогично

2021-11-16 19:52 UTC, dtsaryov commented on project/src/components/adaptor/adaptor.ts
> +      'rating': comment.rate,
В данном случае проще переименовать поля в FilmReview в соответствии с именами объекта, приходящего с сервера, и деструктуризацией в аргументах функции

2021-11-16 19:52 UTC, dtsaryov commented on project/src/components/app/app.tsx
> +{/*  TODO!!!! мне нужно здесь прокидывать пропсы, которые будут использованы в компоненте FilmScreen и его дочерних компонентах- similarFilms, comments? я думаю, что они должны напрямую из стора в ко
Нет, проблема в некорректном экспорте.

Обрати внимание как по умолчанию (export default) экспортируется App, и как FilmScreen

2021-11-16 19:52 UTC, dtsaryov commented on project/src/components/film-screen/film-screen.tsx
> +  // const firstFilm = films[0];
Закомментированный код не держи в репозитории

2021-11-16 19:52 UTC, dtsaryov commented on project/src/components/app/app.tsx
> +{/*  TODO!!!! мне нужно здесь прокидывать пропсы, которые будут использованы в компоненте FilmScreen и его дочерних компонентах- similarFilms, comments? я думаю, что они должны напрямую из стора в ко
После этого можно будет избавиться от пробрасывания кучи всего через иерархию компонентов

2021-11-16 19:52 UTC, dtsaryov commented on project/src/mocks/films.ts
> +  previewImage: 'img/the-grand-budapest-hotel.jpg',
все моки удаляем - они больше не нужны

2021-11-16 19:52 UTC, dtsaryov commented on project/src/components/small-film-card/small-film-card.tsx
> +(store.dispatch as ThunkAppDispatch)(fetchFilmDataAction());
Не надо так делать - сейчас все эти экшены будут вызваны при загрузке модуля, а нам нужно делать это при рендере компонента

2021-11-17 05:35 UTC, samanna27 commented on project/src/components/app/app.tsx
> +{/*  TODO!!!! мне нужно здесь прокидывать пропсы, которые будут использованы в компоненте FilmScreen и его дочерних компонентах- similarFilms, comments? я думаю, что они должны напрямую из стора в ко
поправила экспорт, удалила лишние пропсы

2021-11-17 05:36 UTC, samanna27 commented on project/src/components/film-screen/film-screen.tsx
> +  // const firstFilm = films[0];
удалила

2021-11-17 05:37 UTC, samanna27 commented on project/src/mocks/films.ts
> +  previewImage: 'img/the-grand-budapest-hotel.jpg',
удалю, как без моков заработает, сразу удалю :) может мне этот код еще при написании тестов понадобится :)

2021-11-17 05:54 UTC, samanna27 commented on project/src/mocks/films.ts
> +  previewImage: 'img/the-grand-budapest-hotel.jpg',
удалила

2021-11-17 06:18 UTC, samanna27 commented on project/src/components/adaptor/adaptor.ts
> +      'rating': comment.rate,
для комментариев тип привела в соответствие со структурой данных, которые приходят с сервера

2021-11-25 16:28 UTC, merged